### ISSUE TITLE
Product Enhancements

### ISSUE THREAD

**Issue by lauslim12** [lauslim12/japanese-duolingo-visualizer#1]
## Product Enhancements

Things to be done:

- Create contributing documents: `CONTRIBUTING.md`, `CODE_OF_CONDUCT.md`, and `CHANGELOG.md`.

Done:

- [x] Tests (#2).
- [x] CI/CD for `black`, `isort`, `mypy`, `pytest` (#2).
- [x] Website implementation with design and graph visualization (#3).
- [x] Better API endpoint for daily progression, with faster speed and lesser payload (#4).
- [x] Time graph, which is a feature to draw a graph to visualize time spent in Duolingo (#5).
- [x] Synchronization of essential data (#6).
- [x] Visualize number of sessions (lessons/practices/extras) in a graph (#6).
- [x] Human-readable time format (`XX hours YY minutes`) (#7).
- [x] Show the login/authentication method to the user (#8).
- [x] Separate the methods for logging in and fetching the user's data (#9).
- [x] Diagram and development guidelines (#10).
- [x] Simplify synchronization, part of #11 (#12).
